### ISSUE TITLE
Move to gitter?

### ISSUE THREAD

**Issue by apaszke** [Aweosme/TwitchOS#9]
Since we're trying to write this together how about moving from IRC to [gitter](http://gitter.im)? This way we can read messages even if you were offline when they are sent. It's free for open source projects.

What do you think?

**Comment by ob6160** [comment]
I'm for this, just made a channel #asmosdev :)

**Comment by EliteTK** [comment]
I use an IRC bouncer, if you guys want I can host znc on my server for you all, then we can stay on IRC. Or I can just make my IRC logs available online for the channel. Personally I quite like keeping all my communications in IRC.

**Comment by apaszke** [comment]
Gitter has an IRC interface too, so you can connect to our channel with it. Is that ok?

**Comment by EliteTK** [comment]
You mean I can connect to IRC from gitter?
I would rather not, I extensively use weechat to connect to over 30 channels (and this isn't even much by most hard core irc users' standards) and the TUI is essential, I find GUIs cumbersome and moving all my IRC to gitter would make no sense to me.
If you mean that you can mirror gitter on IRC, sure, where's the information for how to set that up?

**Comment by apaszke** [comment]
[Right here](https://irc.gitter.im) :blush:
